'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Reflection
Imports System.Runtime.InteropServices
Imports System.Security
<Assembly: ComVisibleAttribute(false),  _
 Assembly: CLSCompliantAttribute(true),  _
 Assembly: AssemblyCompanyAttribute("Federal Home Loan Bank of Topeka"),  _
 Assembly: AssemblyVersionAttribute("1.0.0.1604"),  _
 Assembly: AssemblyFileVersionAttribute("1.0.0.1604"),  _
 Assembly: AssemblyInformationalVersionAttribute("1.0.0.1604"),  _
 Assembly: AssemblyTitleAttribute("FHLBank.Demo"),  _
 Assembly: AssemblyProductAttribute("FHLBank.Demo"),  _
 Assembly: AssemblyDescriptionAttribute("FHLBank.Demo is a product for the exclusive use of Federal Home Loan Bank of Tope"& _ 
    "ka."),  _
 Assembly: AssemblyTrademarkAttribute("FHLBank.Demo - Federal Home Loan Bank of Topeka"),  _
 Assembly: AssemblyCopyrightAttribute("Copyright 2010 Federal Home Loan Bank of Topeka, - Original author or authors")> 

