#Region "Header Portion"
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict on
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=4.0.30319.1.
''
'Namespace FHLBank.UamIntegration
#End Region

    <System.Web.Services.WebService(Namespace:="http://namespace.fhlbsea.com/webservices/")> _
    <System.Web.Services.WebServiceBinding(ConformsTo:=WsiProfiles.BasicProfile1_1)> _
     Partial Public Class UAMDirectoryServices
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
    #Region "Private Variables"
        Private ListApplicationErrorsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListStatesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListCountiesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListApplicationsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListUserApplicationsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListAssignableApplicationsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListAssignableApplicationInstitutionsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListAssignableApplicationRolesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListAssignableApplicationInstitutionRolesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListApplicationRolesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListUserApplicationRolesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListUserApplicationInstitutionRolesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListDepartmentsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListInstitutionsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListInstitutionsByTypeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListUserInstitutionsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetExternalUsersForInstitutionAndRolesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListInstitutionUsersOperationCompleted As System.Threading.SendOrPostCallback
        
        Private IsInternalFHLBUserOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetLandingPageLinkDisplayOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListInstitutionsByNameOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListUserApplicationInstitutionsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListUsersOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListUserAdministratorsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListUserAccountsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ResetPasswordOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetUserAccountOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetApplicationRolesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteUserAccountOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateUserAccountOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateUserAccountOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PrepareTaskForDeletionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteUserAccountFromActiveDirectoryOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetInstitutionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetInstitutionsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateInstitutionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateInstitutionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private MergeInstitutionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteInstitutionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListApplicationRoleUsersOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListGroupUsersOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListUserGroupsOperationCompleted As System.Threading.SendOrPostCallback
        #End Region
        
        #Region "Events"
        '''<remarks/>
        Public Event ListApplicationErrorsCompleted As ListApplicationErrorsCompletedEventHandler
        
        '''<remarks/>
        Public Event ListStatesCompleted As ListStatesCompletedEventHandler
        
        '''<remarks/>
        Public Event ListCountiesCompleted As ListCountiesCompletedEventHandler
        
        '''<remarks/>
        Public Event ListApplicationsCompleted As ListApplicationsCompletedEventHandler
        
        '''<remarks/>
        Public Event ListUserApplicationsCompleted As ListUserApplicationsCompletedEventHandler
        
        '''<remarks/>
        Public Event ListAssignableApplicationsCompleted As ListAssignableApplicationsCompletedEventHandler
        
        '''<remarks/>
        Public Event ListAssignableApplicationInstitutionsCompleted As ListAssignableApplicationInstitutionsCompletedEventHandler
        
        '''<remarks/>
        Public Event ListAssignableApplicationRolesCompleted As ListAssignableApplicationRolesCompletedEventHandler
        
        '''<remarks/>
        Public Event ListAssignableApplicationInstitutionRolesCompleted As ListAssignableApplicationInstitutionRolesCompletedEventHandler
        
        '''<remarks/>
        Public Event ListApplicationRolesCompleted As ListApplicationRolesCompletedEventHandler
        
        '''<remarks/>
        Public Event ListUserApplicationRolesCompleted As ListUserApplicationRolesCompletedEventHandler
        
        '''<remarks/>
        Public Event ListUserApplicationInstitutionRolesCompleted As ListUserApplicationInstitutionRolesCompletedEventHandler
        
        '''<remarks/>
        Public Event ListDepartmentsCompleted As ListDepartmentsCompletedEventHandler
        
        '''<remarks/>
        Public Event ListInstitutionsCompleted As ListInstitutionsCompletedEventHandler
        
        '''<remarks/>
        Public Event ListInstitutionsByTypeCompleted As ListInstitutionsByTypeCompletedEventHandler
        
        '''<remarks/>
        Public Event ListUserInstitutionsCompleted As ListUserInstitutionsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetExternalUsersForInstitutionAndRolesCompleted As GetExternalUsersForInstitutionAndRolesCompletedEventHandler
        
        '''<remarks/>
        Public Event ListInstitutionUsersCompleted As ListInstitutionUsersCompletedEventHandler
        
        '''<remarks/>
        Public Event IsInternalFHLBUserCompleted As IsInternalFHLBUserCompletedEventHandler
        
        '''<remarks/>
        Public Event GetLandingPageLinkDisplayCompleted As GetLandingPageLinkDisplayCompletedEventHandler
        
        '''<remarks/>
        Public Event ListInstitutionsByNameCompleted As ListInstitutionsByNameCompletedEventHandler
        
        '''<remarks/>
        Public Event ListUserApplicationInstitutionsCompleted As ListUserApplicationInstitutionsCompletedEventHandler
        
        '''<remarks/>
        Public Event ListUsersCompleted As ListUsersCompletedEventHandler
        
        '''<remarks/>
        Public Event ListUserAdministratorsCompleted As ListUserAdministratorsCompletedEventHandler
        
        '''<remarks/>
        Public Event ListUserAccountsCompleted As ListUserAccountsCompletedEventHandler
        
        '''<remarks/>
        Public Event ResetPasswordCompleted As ResetPasswordCompletedEventHandler
        
        '''<remarks/>
        Public Event GetUserAccountCompleted As GetUserAccountCompletedEventHandler
        
        '''<remarks/>
        Public Event GetApplicationRolesCompleted As GetApplicationRolesCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteUserAccountCompleted As DeleteUserAccountCompletedEventHandler
        
        '''<remarks/>
        Public Event CreateUserAccountCompleted As CreateUserAccountCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateUserAccountCompleted As UpdateUserAccountCompletedEventHandler
        
        '''<remarks/>
        Public Event PrepareTaskForDeletionCompleted As PrepareTaskForDeletionCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteUserAccountFromActiveDirectoryCompleted As DeleteUserAccountFromActiveDirectoryCompletedEventHandler
        
        '''<remarks/>
        Public Event GetInstitutionCompleted As GetInstitutionCompletedEventHandler
        
        '''<remarks/>
        Public Event GetInstitutionsCompleted As GetInstitutionsCompletedEventHandler
        
        '''<remarks/>
        Public Event CreateInstitutionCompleted As CreateInstitutionCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateInstitutionCompleted As UpdateInstitutionCompletedEventHandler
        
        '''<remarks/>
        Public Event MergeInstitutionCompleted As MergeInstitutionCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteInstitutionCompleted As DeleteInstitutionCompletedEventHandler
        
        '''<remarks/>
        Public Event ListApplicationRoleUsersCompleted As ListApplicationRoleUsersCompletedEventHandler
        
        '''<remarks/>
        Public Event ListGroupUsersCompleted As ListGroupUsersCompletedEventHandler
        
        '''<remarks/>
        Public Event ListUserGroupsCompleted As ListUserGroupsCompletedEventHandler
        
    #End Region
        
        #Region "ListApplicationErrors"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListApplicationErrors", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListApplicationErrors(ByVal fromDateTime As Date, ByVal toDateTime As Date) As ApplicationError()
            Dim results() As Object = Me.Invoke("ListApplicationErrors", New Object() {fromDateTime, toDateTime})
            Return CType(results(0),ApplicationError())
        End Function
        #End Region
     
        #Region "ListStates"
       <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListStates", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListStates() As State()
            Dim results() As Object = Me.Invoke("ListStates", New Object(-1) {})
            Return CType(results(0),State())
        End Function
        #End Region
        
        #Region "ListCounties"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListCounties", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListCounties(ByVal stateCode As String) As County()
            Dim results() As Object = Me.Invoke("ListCounties", New Object() {stateCode})
            Return CType(results(0),County())
        End Function
        #End Region

        #Region "ListApplications"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListApplications", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListApplications() As EntityReference()
            Dim results() As Object = Me.Invoke("ListApplications", New Object(-1) {})
            Return CType(results(0),EntityReference())
        End Function
        #End Region
        
        #Region "ListUserApplications"
         <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListUserApplications", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListUserApplications(ByVal userName As String) As EntityReference()
            Dim results() As Object = Me.Invoke("ListUserApplications", New Object() {userName})
            Return CType(results(0),EntityReference())
        End Function
  
        #End Region

        #Region "ListAssignableApplications"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListAssignableApplications", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListAssignableApplications(ByVal userName As String) As EntityReference()
            Dim results() As Object = Me.Invoke("ListAssignableApplications", New Object() {userName})
            Return CType(results(0),EntityReference())
        End Function
        #End Region    
        
        #Region "ListAssignableApplicationInstitutions"
      <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListAssignableApplicationInstitutions", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListAssignableApplicationInstitutions(ByVal applicationID As String, ByVal userName As String) As EntityReference()
            Dim results() As Object = Me.Invoke("ListAssignableApplicationInstitutions", New Object() {applicationID, userName})
            Return CType(results(0),EntityReference())
        End Function
        #End Region    
        
        #Region "ListAssignableApplicationRoles"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListAssignableApplicationRoles", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListAssignableApplicationRoles(ByVal applicationID As String, ByVal userName As String) As EntityReference()
            Dim results() As Object = Me.Invoke("ListAssignableApplicationRoles", New Object() {applicationID, userName})
            Return CType(results(0),EntityReference())
        End Function
        #End Region    
        
        #Region "ListAssignableApplicationInstitutionRoles"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListAssignableApplicationInstitutionRole"& _ 
            "s", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListAssignableApplicationInstitutionRoles(ByVal applicationID As String, ByVal userName As String, ByVal institutionID As String) As EntityReference()
            Dim results() As Object = Me.Invoke("ListAssignableApplicationInstitutionRoles", New Object() {applicationID, userName, institutionID})
            Return CType(results(0),EntityReference())
        End Function
        #End Region    
        
        #Region "ListApplicationRoles"
         <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListApplicationRoles", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListApplicationRoles(ByVal applicationID As String, ByVal scope As PermissionScope) As EntityReference()
            Dim results() As Object = Me.Invoke("ListApplicationRoles", New Object() {applicationID, scope})
            Return CType(results(0),EntityReference())
        End Function
        #End Region
    
        #Region "ListUserApplicationRoles"
         <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListUserApplicationRoles", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListUserApplicationRoles(ByVal applicationID As String, ByVal userName As String) As EntityReference()
            Dim results() As Object = Me.Invoke("ListUserApplicationRoles", New Object() {applicationID, userName})
            Return CType(results(0),EntityReference())
        End Function
        #End Region
    
        #Region "ListUserApplicationInstitutionRoles"
         <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListUserApplicationInstitutionRoles", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListUserApplicationInstitutionRoles(ByVal applicationID As String, ByVal userName As String, ByVal institutionID As String) As EntityReference()
            Dim results() As Object = Me.Invoke("ListUserApplicationInstitutionRoles", New Object() {applicationID, userName, institutionID})
            Return CType(results(0),EntityReference())
        End Function
        #End Region

        #Region "ListDepartments"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListDepartments", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListDepartments() As EntityReference()
            Dim results() As Object = Me.Invoke("ListDepartments", New Object(-1) {})
            Return CType(results(0),EntityReference())
        End Function
        #End Region

        #Region "ListInstitutions"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListInstitutions", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListInstitutions() As Institution()
            Dim results() As Object = Me.Invoke("ListInstitutions", New Object(-1) {})
            Return CType(results(0),Institution())
        End Function
        #End Region
        
        #Region "ListInstitutionsByType"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListInstitutionsByType", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListInstitutionsByType(ByVal type As InstitutionType) As Institution()
            Dim results() As Object = Me.Invoke("ListInstitutionsByType", New Object() {type})
            Return CType(results(0),Institution())
        End Function
        #End Region

        #Region "ListUserInstitutions"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListUserInstitutions", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListUserInstitutions(ByVal userName As String) As Institution()
            Dim results() As Object = Me.Invoke("ListUserInstitutions", New Object() {userName})
            Return CType(results(0),Institution())
        End Function
        #End Region

        #Region "GetExternalUsersForInstitutionAndRoles"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/GetExternalUsersForInstitutionAndRoles", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetExternalUsersForInstitutionAndRoles(ByVal institutionID As String, ByVal roles() As System.Guid) As UserAccount()
            Dim results() As Object = Me.Invoke("GetExternalUsersForInstitutionAndRoles", New Object() {institutionID, roles})
            Return CType(results(0),UserAccount())
        End Function
        #End Region
        
        #Region "ListInstitutionUsers"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListInstitutionUsers", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListInstitutionUsers(ByVal institutionID As String) As UserAccount()
            Dim results() As Object = Me.Invoke("ListInstitutionUsers", New Object() {institutionID})
            Return CType(results(0),UserAccount())
        End Function
        #End Region    
        
        #Region "IsInternalFHLBUser" 
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/IsInternalFHLBUser", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsInternalFHLBUser(ByVal [alias] As String) As Boolean
            Dim results() As Object = Me.Invoke("IsInternalFHLBUser", New Object() {[alias]})
            Return CType(results(0),Boolean)
        End Function
        #End Region

        #Region "GetLandingPageLinkDisplay"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/GetLandingPageLinkDisplay", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetLandingPageLinkDisplay(ByVal userAlias As String) As LandingPageLinkDisplay
            Dim results() As Object = Me.Invoke("GetLandingPageLinkDisplay", New Object() {userAlias})
            Return CType(results(0),LandingPageLinkDisplay)
        End Function
        #End Region

        #Region "ListInstitutionsByName"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListInstitutionsByName", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListInstitutionsByName(ByVal institutionID As String) As Institution()
            Dim results() As Object = Me.Invoke("ListInstitutionsByName", New Object() {institutionID})
            Return CType(results(0),Institution())
        End Function
        #End Region

        #Region "ListUserApplicationInstitutions"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListUserApplicationInstitutions", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListUserApplicationInstitutions(ByVal applicationID As String, ByVal userName As String) As EntityReference()
            Dim results() As Object = Me.Invoke("ListUserApplicationInstitutions", New Object() {applicationID, userName})
            Return CType(results(0),EntityReference())
        End Function
        #End Region
        
        #Region "ListUsers"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListUsers", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListUsers(ByVal userName As String) As UserAccount()
            Dim results() As Object = Me.Invoke("ListUsers", New Object() {userName})
            Return CType(results(0),UserAccount())
        End Function
        #End Region
        
        #Region "ListUserAdministrators"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListUserAdministrators", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListUserAdministrators(ByVal userName As String) As UserAccount()
            Dim results() As Object = Me.Invoke("ListUserAdministrators", New Object() {userName})
            Return CType(results(0),UserAccount())
        End Function
        #End Region

        #Region "ListUserAccounts"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListUserAccounts", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListUserAccounts(ByVal firstName As String, ByVal secondName As String, ByVal institutionString As String, ByVal institutions() As Institution) As UserAccount()
            Dim results() As Object = Me.Invoke("ListUserAccounts", New Object() {firstName, secondName, institutionString, institutions})
            Return CType(results(0),UserAccount())
        End Function
        #End Region

        #Region "ResetPassword"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ResetPassword", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub ResetPassword(ByVal userName As String, ByVal newPassword As String)
            Me.Invoke("ResetPassword", New Object() {userName, newPassword})
        End Sub
        #End Region

        #Region "GetUserAccount"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/GetUserAccount", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUserAccount(ByVal userName As String) As UserAccount
            Dim results() As Object = Me.Invoke("GetUserAccount", New Object() {userName})
            Return CType(results(0),UserAccount)
        End Function
        #End Region

        #Region "GetApplicationRoles"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/GetApplicationRoles", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetApplicationRoles(ByVal applicationID As String) As ApplicationRole()
            Dim results() As Object = Me.Invoke("GetApplicationRoles", New Object() {applicationID})
            Return CType(results(0),ApplicationRole())
        End Function
        #End Region

        #Region "DeleteUserAccount"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/DeleteUserAccount", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub DeleteUserAccount(ByVal contactID As System.Guid)
            Me.Invoke("DeleteUserAccount", New Object() {contactID})
        End Sub
        #End Region

        #Region "CreateUserAccount"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/CreateUserAccount", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreateUserAccount(ByVal user As UserAccount, ByVal password As String) As UserAccount
            Dim results() As Object = Me.Invoke("CreateUserAccount", New Object() {user, password})
            Return CType(results(0),UserAccount)
        End Function
        #End Region

        #Region "UpdateUserAccount"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/UpdateUserAccount", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateUserAccount(ByVal user As UserAccount, ByVal notifyTaskWorkflow As Boolean) As UserAccount
            Dim results() As Object = Me.Invoke("UpdateUserAccount", New Object() {user, notifyTaskWorkflow})
            Return CType(results(0),UserAccount)
        End Function
        #End Region
      
        #Region "PrepareTaskForDeletion"
          <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/PrepareTaskForDeletion", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PrepareTaskForDeletion(ByVal userName As String) As Boolean
            Dim results() As Object = Me.Invoke("PrepareTaskForDeletion", New Object() {userName})
            Return CType(results(0),Boolean)
        End Function
        
        #End Region

        #Region "DeleteUserAccountFromActiveDirectory"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/DeleteUserAccountFromActiveDirectory", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub DeleteUserAccountFromActiveDirectory(ByVal userName As String)
            Me.Invoke("DeleteUserAccountFromActiveDirectory", New Object() {userName})
        End Sub
       
        #End Region
        
        #Region "GetInstitution"
         <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/GetInstitution", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetInstitution(ByVal institutionID As String) As Institution
            Dim results() As Object = Me.Invoke("GetInstitution", New Object() {institutionID})
            Return CType(results(0),Institution)
        End Function
        
        
        #End Region

        #Region "GetInstitutions"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/GetInstitutions", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetInstitutions() As Institution()
            Dim results() As Object = Me.Invoke("GetInstitutions", New Object(-1) {})
            Return CType(results(0),Institution())
        End Function
      
        #End Region

        #Region "CreateInstitution"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/CreateInstitution", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreateInstitution(ByVal institution As Institution) As Institution
            Dim results() As Object = Me.Invoke("CreateInstitution", New Object() {institution})
            Return CType(results(0),Institution)
        End Function
        #End Region
        
        #Region "UpdateInstitution"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/UpdateInstitution", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateInstitution(ByVal institution As Institution) As Institution
            Dim results() As Object = Me.Invoke("UpdateInstitution", New Object() {institution})
            Return CType(results(0),Institution)
        End Function
         #End Region    

        #Region "MergeInstitution"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/MergeInstitution", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function MergeInstitution(ByVal acquiredInsitution As InstitutionData, ByVal acquiringInstitution As InstitutionData) As InstitutionData
            Dim results() As Object = Me.Invoke("MergeInstitution", New Object() {acquiredInsitution, acquiringInstitution})
            Return CType(results(0),InstitutionData)
        End Function
         #End Region
        
        #Region "DeleteInstitution"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/DeleteInstitution", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub DeleteInstitution(ByVal institutionID As String)
            Me.Invoke("DeleteInstitution", New Object() {institutionID})
        End Sub
         #End Region
        
        #Region "ListApplicationRoleUsers"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListApplicationRoleUsers", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListApplicationRoleUsers(ByVal applicationRoleID As String) As EntityReference()
            Dim results() As Object = Me.Invoke("ListApplicationRoleUsers", New Object() {applicationRoleID})
            Return CType(results(0),EntityReference())
        End Function
         #End Region
        
        #Region "ListGroupUsers"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListGroupUsers", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListGroupUsers(ByVal groupName As String) As User()
            Dim results() As Object = Me.Invoke("ListGroupUsers", New Object() {groupName})
            Return CType(results(0),User())
        End Function
         #End Region    

        #Region "ListUserGroups"
        <WebMethod()> _
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://namespace.fhlbsea.com/webservices/ListUserGroups", RequestNamespace:="http://namespace.fhlbsea.com/webservices/", ResponseNamespace:="http://namespace.fhlbsea.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListUserGroups(ByVal loggedUser As String) As String()
            Dim results() As Object = Me.Invoke("ListUserGroups", New Object() {loggedUser})
            Return CType(results(0),String())
        End Function
        #End Region

        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost:58726/DirectoryServices.asmx"
        End Sub
    End Class
    
